version: "3.7"

services:
  reverse-proxy:
    image: "traefik:v2.9"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.reverse-proxy-http.address=:80"
      - "--entrypoints.reverse-proxy-https.address=:443"

  api:
    build: api/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.api-http.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.api-https.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api-https.tls=true"

  ui:
    build: ui/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.ui-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.ui-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui-https.tls=true"
    volumes:
      - ./config-api-url:/usr/share/nginx/html/config/api-url
